[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Context filetype library
repo = 'Shougo/context_filetype.vim'

[[plugins]] # Provide pseudo "clipboard" registers
repo = 'kana/vim-fakeclip'

#[[plugins]] # color scheme
#repo = 'w0ng/vim-hybrid'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''
